camera: hik

odom2camera:
  xyz: "\"0.0481 0.00 0.047\""
  rpy: "\"0.0  ${pi/360}  ${pi/180}\""

detector_log_level: INFO
tracker_log_level: INFO
serial_log_level: INFO
front_assist_detector_log_level: INFO
front_assist_tracker_log_level: INFO
back_assist_detector_log_level: INFO
back_assist_tracker_log_level: INFO

