camera: hik

odom2camera:
  xyz: "\"0.000 0.000  0.000\""
  rpy: "\"0.0  0.0  0.0\""

detector_log_level: INFO
tracker_log_level: INFO
serial_log_level: INFO
front_assist_detector_log_level: INFO
front_assist_tracker_log_level: INFO
back_assist_detector_log_level: INFO
back_assist_tracker_log_level: INFO

